In [152]:
import pandas as pd

In [153]:
df_2026 = pd.read_csv("C:\\Coding\\hospital-bed-forecast\\data\\raw\\populasi tiap propinsi 2023.csv")
df_2026.tail(10)

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (Km2),Rasio Jenis Kelamin Penduduk
32,Papua Barat,1187.3,1.68,0.43,12,110.1
33,Papua Barat Daya,...,...,...,...,...
34,Papua,4482.7,1.49,1.61,14,112.9
35,Papua Selatan,...,...,...,...,...
36,Papua Tengah,...,...,...,...,...
37,Papua Pegunungan,...,...,...,...,...
38,Indonesia,278696.2,1.13,100,147,102.1
39,NaN,NaN,NaN,NaN,NaN,NaN
40,Keterangan,NaN,NaN,NaN,NaN,NaN
41,<sup>1</sup> Hasil Proyeksi Penduduk Indonesia...,NaN,NaN,NaN,NaN,NaN

In [154]:
df_2026 = df_2026.dropna()
df_2026 = df_2026.replace('...', 0)
df_2026["Jumlah Penduduk (Ribu)"] = df_2026["Jumlah Penduduk (Ribu)"].astype(float)
df_2026["Jumlah Penduduk (Ribu)"] = df_2026["Jumlah Penduduk (Ribu)"] * 1000
df_2026["Jumlah Penduduk (Ribu)"] = df_2026["Jumlah Penduduk (Ribu)"].astype(int)
df_2026.tail(10)

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (Km2),Rasio Jenis Kelamin Penduduk
29,Sulawesi Barat,1481100,1.56,0.53,89,102.8
30,Maluku,1920500,1.39,0.69,42,102.4
31,Maluku Utara,1337100,1.52,0.48,41,105.1
32,Papua Barat,1187300,1.68,0.43,12,110.1
33,Papua Barat Daya,0,0,0,0,0
34,Papua,4482700,1.49,1.61,14,112.9
35,Papua Selatan,0,0,0,0,0
36,Papua Tengah,0,0,0,0,0
37,Papua Pegunungan,0,0,0,0,0
38,Indonesia,278696200,1.13,100,147,102.1

In [155]:
df_2026 = df_2026.rename(columns={
    "Jumlah Penduduk (Ribu)": "Jumlah Penduduk 2026",
    "Laju Pertumbuhan Penduduk per Tahun": "LPP 2026"
})
df_2026 = df_2026.drop(columns=["Persentase Penduduk", "Kepadatan Penduduk per km persegi (Km2)", "Rasio Jenis Kelamin Penduduk"])

In [156]:
df_2026.head()

         Provinsi  Jumlah Penduduk 2026 LPP 2026
0            Aceh               5482500     1.41
1  Sumatera Utara              15386600     1.43
2  Sumatera Barat               5757200     1.45
3            Riau               6642900      1.4
4           Jambi               3679200     1.33

In [157]:
df_2026[('Jumlah Penduduk 2026')] = df_2026[('Jumlah Penduduk 2026')].astype(int)

In [158]:
def population_data_cleaning(filename, year):
    data = "C:\\Coding\\hospital-bed-forecast\\data\\raw\\" + filename
    df = pd.read_csv(data)
    df = df.dropna()
    df = df.replace("...", 0)
    df = df.replace("–", 0)
    df["Jumlah Penduduk (Ribu)"] = df["Jumlah Penduduk (Ribu)"].astype(float)
    df["Jumlah Penduduk (Ribu)"] = df["Jumlah Penduduk (Ribu)"] * 1000
    df["Jumlah Penduduk (Ribu)"] = df["Jumlah Penduduk (Ribu)"].astype(int)
    df = df.rename(columns={
        "Jumlah Penduduk (Ribu)": ("Jumlah Penduduk " + year),
        "Laju Pertumbuhan Penduduk per Tahun": ("LPP " + year)
    })
    df = df.drop(columns=["Persentase Penduduk", "Kepadatan Penduduk per km persegi (Km2)", "Rasio Jenis Kelamin Penduduk"])
    df[("LPP " + year)] = df[("LPP " + year)].astype(str).str.replace(r'[^\d.-]', '', regex=True)
    df[("LPP " + year)] = df[("LPP " + year)].astype(float)

    return df

In [159]:
df_2025 = population_data_cleaning("populasi tiap propinsi 2025.csv", "2025")
df_2025.head()

         Provinsi  Jumlah Penduduk 2025  LPP 2025
0            Aceh               5626000      1.37
1  Sumatera Utara              15785800      1.37
2  Sumatera Barat               5914300      1.41
3            Riau               6811200      1.34
4           Jambi               3768500      1.28

In [160]:
df_2024 = population_data_cleaning("populasi tiap propinsi 2024.csv", "2024")
df_2024.head()

         Provinsi  Jumlah Penduduk 2024  LPP 2024
0            Aceh               5554800      1.39
1  Sumatera Utara              15588500      1.40
2  Sumatera Barat               5836200      1.43
3            Riau               6728100      1.37
4           Jambi               3724300      1.30

In [161]:
df_2023 = population_data_cleaning("populasi tiap propinsi 2023.csv", "2023")
df_2023.head()

         Provinsi  Jumlah Penduduk 2023  LPP 2023
0            Aceh               5482500      1.41
1  Sumatera Utara              15386600      1.43
2  Sumatera Barat               5757200      1.45
3            Riau               6642900      1.40
4           Jambi               3679200      1.33

In [162]:
df_2022 = population_data_cleaning("populasi tiap propinsi 2022.csv", "2022")
df_2022.head()

         Provinsi  Jumlah Penduduk 2022  LPP 2022
0            Aceh               5407900      1.43
1  Sumatera Utara              15115200      1.21
2  Sumatera Barat               5640600      1.09
3            Riau               6614400      1.95
4           Jambi               3631100      1.33

In [163]:
df_2021 = population_data_cleaning("populasi tiap propinsi 2021.csv", "2021")
df_2021.head()

         Provinsi  Jumlah Penduduk 2021  LPP 2021
0            Aceh               5333700      1.49
1  Sumatera Utara              14936200      1.23
2  Sumatera Barat               5580200      1.10
3            Riau               6493600      2.08
4           Jambi               3585100      1.39

In [164]:
df_2020 = population_data_cleaning("populasi tiap propinsi 2020.csv", "2020")
df_2020.head()

         Provinsi  Jumlah Penduduk 2020  LPP 2020
0            Aceh               5274900      1.56
1  Sumatera Utara              14799400      1.28
2  Sumatera Barat               5534500      1.29
3            Riau               6394100      1.40
4           Jambi               3548200      1.34

In [165]:
df_2019 = population_data_cleaning("populasi tiap propinsi 2019.csv", "2019")
df_2019.head()

         Provinsi  Jumlah Penduduk 2019  LPP 2019
0            Aceh               5371500      1.93
1  Sumatera Utara              14562500      1.24
2  Sumatera Barat               5441200      1.25
3            Riau               6971700      2.52
4           Jambi               3624600      1.72

In [166]:
df_2018 = population_data_cleaning("populasi tiap propinsi 2018.csv", "2018")
df_2018.head()

         Provinsi  Jumlah Penduduk 2018  LPP 2018
0            Aceh               5281300      1.96
1  Sumatera Utara              14415400      1.27
2  Sumatera Barat               5382100      1.27
3            Riau               6814900      2.54
4           Jambi               3570300      1.75

In [167]:
df_2017 = population_data_cleaning("populasi tiap propinsi 2017.csv", "2017")
df_2017.head()

         Provinsi  Jumlah Penduduk 2017  LPP 2017
0            Aceh               5189500      1.98
1  Sumatera Utara              14262100      1.30
2  Sumatera Barat               5321500      1.29
3            Riau               6657900      2.57
4           Jambi               3515000      1.78

In [168]:
df_2016 = population_data_cleaning("populasi tiap propinsi 2016.csv", "2016")
df_2016.head()

         Provinsi  Jumlah Penduduk 2016  LPP 2016
0            Aceh               5096200      2.01
1  Sumatera Utara              14102900      1.33
2  Sumatera Barat               5259500      1.31
3            Riau               6501000      2.59
4           Jambi               3458900      1.80

In [ ]:
df_2010 = population_data_cleaning("populasi tiap propinsi 2010.csv", "2010")
df_2010.head()

str

         Provinsi  Jumlah Penduduk 2010  LPP 2010
0            Aceh               4494400      2.36
1  Sumatera Utara              12982200      1.10
2  Sumatera Barat               4846900      1.34
3            Riau               5538400      3.58
4           Jambi               3092300      2.56