In [161]:
import pandas as pd
import numpy as np

In [162]:
df_2026 = pd.read_csv("C:\\Coding\\hospital-bed-forecast\\data\\raw\\populasi tiap propinsi 2023.csv")
df_2026.tail(10)

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (Km2),Rasio Jenis Kelamin Penduduk
32,Papua Barat,1187.3,1.68,0.43,12,110.1
33,Papua Barat Daya,...,...,...,...,...
34,Papua,4482.7,1.49,1.61,14,112.9
35,Papua Selatan,...,...,...,...,...
36,Papua Tengah,...,...,...,...,...
37,Papua Pegunungan,...,...,...,...,...
38,Indonesia,278696.2,1.13,100,147,102.1
39,NaN,NaN,NaN,NaN,NaN,NaN
40,Keterangan,NaN,NaN,NaN,NaN,NaN
41,<sup>1</sup> Hasil Proyeksi Penduduk Indonesia...,NaN,NaN,NaN,NaN,NaN

In [163]:
df_2026 = df_2026.dropna()
df_2026 = df_2026.replace('...', 0)
df_2026["Jumlah Penduduk (Ribu)"] = df_2026["Jumlah Penduduk (Ribu)"].astype(float)
df_2026["Jumlah Penduduk (Ribu)"] = df_2026["Jumlah Penduduk (Ribu)"] * 1000
df_2026["Jumlah Penduduk (Ribu)"] = df_2026["Jumlah Penduduk (Ribu)"].astype(int)
df_2026.tail(10)

,Provinsi,Jumlah Penduduk (Ribu),Laju Pertumbuhan Penduduk per Tahun,Persentase Penduduk,Kepadatan Penduduk per km persegi (Km2),Rasio Jenis Kelamin Penduduk
29,Sulawesi Barat,1481100,1.56,0.53,89,102.8
30,Maluku,1920500,1.39,0.69,42,102.4
31,Maluku Utara,1337100,1.52,0.48,41,105.1
32,Papua Barat,1187300,1.68,0.43,12,110.1
33,Papua Barat Daya,0,0,0,0,0
34,Papua,4482700,1.49,1.61,14,112.9
35,Papua Selatan,0,0,0,0,0
36,Papua Tengah,0,0,0,0,0
37,Papua Pegunungan,0,0,0,0,0
38,Indonesia,278696200,1.13,100,147,102.1

In [164]:
df_2026 = df_2026.rename(columns={
    "Jumlah Penduduk (Ribu)": "Jumlah Penduduk 2026",
    "Laju Pertumbuhan Penduduk per Tahun": "LPP 2026"
})
df_2026 = df_2026.drop(columns=["Persentase Penduduk", "Kepadatan Penduduk per km persegi (Km2)", "Rasio Jenis Kelamin Penduduk"])

In [165]:
df_2026.head()

         Provinsi  Jumlah Penduduk 2026 LPP 2026
0            Aceh               5482500     1.41
1  Sumatera Utara              15386600     1.43
2  Sumatera Barat               5757200     1.45
3            Riau               6642900      1.4
4           Jambi               3679200     1.33

In [166]:
df_2026[('Jumlah Penduduk 2026')] = df_2026[('Jumlah Penduduk 2026')].astype(int)

In [167]:
def population_data_cleaning(filename, year):
    data = "C:\\Coding\\hospital-bed-forecast\\data\\raw\\" + filename
    df = pd.read_csv(data)
    df = df.dropna()
    df = df.replace("...", 0)
    df = df.replace("–", 0)
    df["Jumlah Penduduk (Ribu)"] = df["Jumlah Penduduk (Ribu)"].astype(float)
    df["Jumlah Penduduk (Ribu)"] = df["Jumlah Penduduk (Ribu)"] * 1000
    df["Jumlah Penduduk (Ribu)"] = df["Jumlah Penduduk (Ribu)"].astype(int)
    df = df.rename(columns={
        "Jumlah Penduduk (Ribu)": ("Jumlah Penduduk " + year),
        "Laju Pertumbuhan Penduduk per Tahun": ("LPP " + year)
    })
    df = df.drop(columns=["Persentase Penduduk", "Kepadatan Penduduk per km persegi (Km2)", "Rasio Jenis Kelamin Penduduk"])
    df[("LPP " + year)] = df[("LPP " + year)].astype(str).str.replace(r'[^\d.-]', '', regex=True)
    df[("LPP " + year)] = df[("LPP " + year)].astype(float)

    return df

In [168]:
df_2025 = population_data_cleaning("populasi tiap propinsi 2025.csv", "2025")
df_2025.head()

         Provinsi  Jumlah Penduduk 2025  LPP 2025
0            Aceh               5626000      1.37
1  Sumatera Utara              15785800      1.37
2  Sumatera Barat               5914300      1.41
3            Riau               6811200      1.34
4           Jambi               3768500      1.28

In [169]:
df_2024 = population_data_cleaning("populasi tiap propinsi 2024.csv", "2024")
df_2024.head()

         Provinsi  Jumlah Penduduk 2024  LPP 2024
0            Aceh               5554800      1.39
1  Sumatera Utara              15588500      1.40
2  Sumatera Barat               5836200      1.43
3            Riau               6728100      1.37
4           Jambi               3724300      1.30

In [170]:
df_2023 = population_data_cleaning("populasi tiap propinsi 2023.csv", "2023")
df_2023.head()

         Provinsi  Jumlah Penduduk 2023  LPP 2023
0            Aceh               5482500      1.41
1  Sumatera Utara              15386600      1.43
2  Sumatera Barat               5757200      1.45
3            Riau               6642900      1.40
4           Jambi               3679200      1.33

In [171]:
df_2022 = population_data_cleaning("populasi tiap propinsi 2022.csv", "2022")
df_2022.head()

         Provinsi  Jumlah Penduduk 2022  LPP 2022
0            Aceh               5407900      1.43
1  Sumatera Utara              15115200      1.21
2  Sumatera Barat               5640600      1.09
3            Riau               6614400      1.95
4           Jambi               3631100      1.33

In [172]:
df_2021 = population_data_cleaning("populasi tiap propinsi 2021.csv", "2021")
df_2021.head()

         Provinsi  Jumlah Penduduk 2021  LPP 2021
0            Aceh               5333700      1.49
1  Sumatera Utara              14936200      1.23
2  Sumatera Barat               5580200      1.10
3            Riau               6493600      2.08
4           Jambi               3585100      1.39

In [173]:
df_2020 = population_data_cleaning("populasi tiap propinsi 2020.csv", "2020")
df_2020.head()

         Provinsi  Jumlah Penduduk 2020  LPP 2020
0            Aceh               5274900      1.56
1  Sumatera Utara              14799400      1.28
2  Sumatera Barat               5534500      1.29
3            Riau               6394100      1.40
4           Jambi               3548200      1.34

In [174]:
df_2019 = population_data_cleaning("populasi tiap propinsi 2019.csv", "2019")
df_2019.head()

         Provinsi  Jumlah Penduduk 2019  LPP 2019
0            Aceh               5371500      1.93
1  Sumatera Utara              14562500      1.24
2  Sumatera Barat               5441200      1.25
3            Riau               6971700      2.52
4           Jambi               3624600      1.72

In [175]:
df_2018 = population_data_cleaning("populasi tiap propinsi 2018.csv", "2018")
df_2018.head()

         Provinsi  Jumlah Penduduk 2018  LPP 2018
0            Aceh               5281300      1.96
1  Sumatera Utara              14415400      1.27
2  Sumatera Barat               5382100      1.27
3            Riau               6814900      2.54
4           Jambi               3570300      1.75

In [176]:
df_2017 = population_data_cleaning("populasi tiap propinsi 2017.csv", "2017")
df_2017.head()

         Provinsi  Jumlah Penduduk 2017  LPP 2017
0            Aceh               5189500      1.98
1  Sumatera Utara              14262100      1.30
2  Sumatera Barat               5321500      1.29
3            Riau               6657900      2.57
4           Jambi               3515000      1.78

In [177]:
df_2016 = population_data_cleaning("populasi tiap propinsi 2016.csv", "2016")
df_2016.head()

         Provinsi  Jumlah Penduduk 2016  LPP 2016
0            Aceh               5096200      2.01
1  Sumatera Utara              14102900      1.33
2  Sumatera Barat               5259500      1.31
3            Riau               6501000      2.59
4           Jambi               3458900      1.80

In [178]:
df_2010 = population_data_cleaning("populasi tiap propinsi 2010.csv", "2010")
df_2010.head()

         Provinsi  Jumlah Penduduk 2010  LPP 2010
0            Aceh               4494400      2.36
1  Sumatera Utara              12982200      1.10
2  Sumatera Barat               4846900      1.34
3            Riau               5538400      3.58
4           Jambi               3092300      2.56

In [179]:
data = "C:\\Coding\\hospital-bed-forecast\\data\\raw\\populasi tiap provinsi 2009-2012.csv"
df_2009_2012 = pd.read_csv(data)
df_2009_2012.head()

         Provinsi        2009        2010        2011        2012  Unnamed: 5
1            Aceh   4 406 990   4 515 792   4 597 308   4 693 934         NaN
2  Sumatera Utara  12 879 189  13 030 601  13 103 596  13 215 401         NaN
3  Sumatera Barat   4 798 051   4 865 912   4 904 460   4 957 719         NaN
4            Riau   5 368 248   5 570 228   5 738 543   5 929 172         NaN
5           Jambi   3 026 376   3 107 486   3 169 814   3 242 814         NaN

In [180]:
df_2009_2012 = df_2009_2012.drop(columns=["2010", "Unnamed: 5"])
df_2009_2012["Provinsi"] = df_2009_2012['Provinsi'].fillna("Indonesia")

In [181]:
df_2009_2012.tail()

               Provinsi         2009         2011         2012
30               Maluku    1 497 429    1 575 965    1 616 046
31         Maluku Utara    1 016 821    1 063 117    1 086 655
32          Papua Barat      736 123      789 013      816 280
33                Papua    2 699 142    2 991 303    3 144 581
Indonesia     Indonesia  234 757 121  241 037 759  244 215 983

In [182]:
for col in ["2009", "2011", "2012"]:
    df_2009_2012[col] = df_2009_2012[col].astype(str).str.replace(' ', '', regex=False).astype(int)

In [183]:
df_2009_2012.tail()

               Provinsi       2009       2011       2012
30               Maluku    1497429    1575965    1616046
31         Maluku Utara    1016821    1063117    1086655
32          Papua Barat     736123     789013     816280
33                Papua    2699142    2991303    3144581
Indonesia     Indonesia  234757121  241037759  244215983

In [187]:
data = "C:\\Coding\\hospital-bed-forecast\\data\\raw\\Laju Pertumbuhan Penduduk menurut Provinsi 2011 -2014.csv"
df_2011_2014 = pd.read_csv(data)
df_2011_2014.tail()

          Provinsi        2010  2011  2012  2013  2014
30  Sulawesi Barat   1 164 574  1,97  1,96  1,94  1,93
31          Maluku   1 541 903  1,86  1,84  1,81  1,78
32    Maluku Utara   1 043 336  2,29  2,24  2,18  2,13
33     Papua Barat     765 258  2,71  2,67  2,64  2,60
34           Papua   2 856 977  2,04  2,01  1,97  1,93

In [188]:
for col in ["2011", "2012", "2013", "2014"]:
    df_2011_2014[col] = df_2011_2014[col].astype(str).str.replace(",", ".", regex=False).astype(float)

df_2011_2014["2010"] = df_2011_2014["2010"].astype(str).str.replace(" ", "", regex=False).astype(int)
df_2011_2014.head()

         Provinsi      2010  2011  2012  2013  2014
1            Aceh   4523144  2.12  2.08  2.04  1.99
2  Sumatera Utara  13028663  1.48  1.42  1.36  1.30
3  Sumatera Barat   4865331  1.39  1.36  1.33  1.29
4            Riau   5574928  2.71  2.67  2.62  2.57
5           Jambi   3107610  1.93  1.88  1.83  1.78

In [189]:
for index, row in df_2011_2014.iterrows():
    pop_2011 = int(np.floor(row["2010"] + ((row["2010"] * row["2011"]) / 100)))
    pop_2012 = int(np.floor(pop_2011 + ((pop_2011 * row["2012"]) / 100)))
    pop_2013 = int(np.floor(pop_2012 + ((pop_2012 * row["2013"]) / 100)))
    pop_2014 = int(np.floor(pop_2013 + ((pop_2013 * row["2014"]) / 100)))
    
    df_2011_2014.at[index, "2011"] = pop_2011
    df_2011_2014.at[index, "2012"] = pop_2012
    df_2011_2014.at[index, "2013"] = pop_2013
    df_2011_2014.at[index, "2014"] = pop_2014

df_2011_2014 = df_2011_2014.drop(columns=["2010", "2011", "2012"])
df_2011_2014["2013"] = df_2011_2014["2013"].astype(int)
df_2011_2014["2014"] = df_2011_2014["2014"].astype(int)
df_2011_2014.head()

         Provinsi      2013      2014
1            Aceh   4811297   4907041
2  Sumatera Utara  13591597  13768287
3  Sumatera Barat   5066547   5131905
4            Riau   6032918   6187963
5           Jambi   3286192   3344686